repositories:
  - name: ocd-meta 
    url: https://ocd-scm.github.io/ocd-meta/charts
releases:
  - name: {{ requiredEnv "ENV_PREFIX" }}-realworld-react-redux
    labels: 
      deployer: {{ requiredEnv "ENV_PREFIX" }}-realworld-react-redux
    chart: ocd-meta/ocd-deployer
    version: ~1.0.0
    values:
      - "values.yaml"
      - imageStreamTag: 172.30.1.1:5000/build-env/realworld-react-redux:v0.0.9