repositories:
  - name: ocd-meta 
    url: https://ocd-scm.github.io/ocd-meta/charts
releases:
  - name: {{ requiredEnv "ENV_PREFIX" }}-realworld-react-redux
    labels: 
      deployer: {{ requiredEnv "ENV_PREFIX" }}-realworld-react-redux
    chart: ocd-meta/ocd-deployer
    version: ~1.0.0
    values:
      - "values.yaml"
      - replicas: 1
      - imageStreamTag: "realworld-react-redux:v0.0.2"
    hooks:
    # FROM, TO, IMAGE, TAG
    - events: ["prepare"]
      command: "ocd-promote-imagestreamtag.sh"
      args: ["env-build", "env-staging", "realworld-react-redux", "v0.0.2"]